// =======================================================================================
// Made by: Rohit Yadav
// NIT Jalandhar
//
// File: compiler_test.cpp
// Purpose:
//   - This file runs the compiled output (`prog.cpp`) using your custom-built VM.
//   - It simulates how a user or interpreter would execute code written in Brolang.
//
// How it works:
//   - Compiles Brolang code into bytecode (instructions).
//   - Loads these instructions into the virtual machine (RohitVM).
//   - Executes and displays the result.
//
// Usage Instructions:
//   g++ broc.cpp lexer.cpp parser.cpp ast.cpp codegen.cpp emitter.cpp -o broc
//   ./broc test.bro -o prog.cpp
//   g++ compiler_test.cpp RohitVM.cpp RohitUtils.cpp -o run_bro
//   ./run_bro
// =======================================================================================

#include "RohitVM.hpp"
#include <iostream>
#include <sstream>

// ---------------------------------------------------------------------------------------
// NOTE:
//   - The file `prog.cpp` is generated by your compiler (broc).
//   - It contains: std::vector<Instruction> prog;
//   - This is the bytecode that will be executed.
// ---------------------------------------------------------------------------------------
#include "prog.cpp"

// =======================================================================================
// Function: runProgram
// Description:
//   - Loads the given instruction list into the VM
//   - Executes the VM and returns formatted output as a string
// Parameters:
//   - prog: vector of compiled instructions (bytecode)
//   - title: a label to print during execution for clarity
// Returns:
//   - A formatted string representing the VM output for the given program
// =======================================================================================
std::string runProgram(const std::vector<Instruction>& prog, const std::string& title) {
    VM vm;
    std::ostringstream out;

    out << "===============================\n";
    out << "Running Compiled Program: " << title << "\n";
    out << "===============================\n";

    vm.loadProgram(prog);
    vm.execute();

    return out.str();
}

// =======================================================================================
// Function: main
// Purpose:
//   - Entry point for running compiled Brolang programs on the custom VM.
//   - Automatically loads `prog.cpp` and runs it.
// =======================================================================================
int main() {
    std::cout << runProgram(prog, "test.bro") << "\n";
    return 0;
}
