#include "RohitVM.hpp"
std::vector<Instruction> prog = {
    {Opcode::MOV, 10},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 3},
    {Opcode::PUSH, 0},
    {Opcode::POP, 2},
    {Opcode::PUSH, 1},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::PUSH, 2},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::ADD},
    {Opcode::PRN},
    {Opcode::MOV, 10},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 3},
    {Opcode::PUSH, 0},
    {Opcode::POP, 2},
    {Opcode::PUSH, 1},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::PUSH, 2},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::DIV},
    {Opcode::PRN},
    {Opcode::MOV, 10},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 3},
    {Opcode::PUSH, 0},
    {Opcode::POP, 2},
    {Opcode::PUSH, 1},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::PUSH, 2},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::SUB},
    {Opcode::PRN},
    {Opcode::MOV, 10},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 3},
    {Opcode::PUSH, 0},
    {Opcode::POP, 2},
    {Opcode::PUSH, 1},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::PUSH, 2},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::MUL},
    {Opcode::PRN},
    {Opcode::PUSH, 1},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::PUSH, 2},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::SUB},
    {Opcode::STG},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 0},
    {Opcode::SUB},
    {Opcode::STE},
    {Opcode::CLE},
    {Opcode::NOP},
    {Opcode::MOV, 999},
    {Opcode::PRN},
    {Opcode::NOP},
    {Opcode::MOV, 111},
    {Opcode::PRN},
    {Opcode::PUSH, 1},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::PUSH, 2},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::SUB},
    {Opcode::STL},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 0},
    {Opcode::SUB},
    {Opcode::STE},
    {Opcode::CLE},
    {Opcode::NOP},
    {Opcode::MOV, 222},
    {Opcode::PRN},
    {Opcode::NOP},
    {Opcode::MOV, 888},
    {Opcode::PRN},
    {Opcode::PUSH, 1},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::PUSH, 2},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::SUB},
    {Opcode::STE},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 0},
    {Opcode::SUB},
    {Opcode::STE},
    {Opcode::CLE},
    {Opcode::NOP},
    {Opcode::MOV, 333},
    {Opcode::PRN},
    {Opcode::NOP},
    {Opcode::MOV, 777},
    {Opcode::PRN},
    {Opcode::MOV, 0},
    {Opcode::PUSH, 0},
    {Opcode::POP, 3},
    {Opcode::PUSH, 3},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::MOV, 3},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::SUB},
    {Opcode::STL},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::MOV, 0},
    {Opcode::SUB},
    {Opcode::STE},
    {Opcode::CLE},
    {Opcode::NOP},
    {Opcode::PUSH, 3},
    {Opcode::POP, 0},
    {Opcode::PRN},
    {Opcode::PUSH, 3},
    {Opcode::POP, 0},
    {Opcode::PUSH, 0},
    {Opcode::MOV, 1},
    {Opcode::PUSH, 0},
    {Opcode::POP, 1},
    {Opcode::POP, 0},
    {Opcode::ADD},
    {Opcode::PUSH, 0},
    {Opcode::POP, 3},
    {Opcode::NOP},
    {Opcode::HLT},
};
